import type { Activity, Lead } from "./types";

export const leadsSeed: Lead[] = [
  {
    id: "lead-joao",
    fullName: "João Silva",
    cpf: "022.455.123-90",
    phone: "(89) 99412-1802",
    city: "São José do Piauí",
    email: "joao.silva@email.com",
    birthDate: "1993-08-18",
    hasCnh: true,
    cnhCategory: "AB",
    model: "AZ160 Xtreme",
    desiredColor: "Azul",
    downPayment: 2500,
    paymentMethod: "Financiamento",
    seller: "Rafael",
    status: "Aguardando Cliente",
    bank: "Banco Pan",
    lastResult: "Negado",
    nextActionDate: "2026-07-15",
    nextActionReason: "Score baixo",
    notes: "Cliente trabalha com entregas e quer trocar de moto ainda este mês.",
    visitedStore: true,
    respondsWhatsapp: true,
    returnedContact: true,
    boughtElsewhere: false,
    lastContactDate: "2026-07-10",
    createdAt: "2026-06-02",
    simulations: [
      {
        id: "sim-joao-1",
        date: "2026-06-03",
        bank: "Banco Pan",
        result: "Negado",
        downPayment: 1500,
        denialReason: "Score baixo",
        nextActionDate: "2026-07-15",
        notes: "Orientado a aguardar 60 dias e tentar nova entrada.",
      },
    ],
    timeline: [
      {
        id: "tl-joao-1",
        date: "2026-06-02",
        title: "Lead criado",
        description: "Entrada pelo formulário do site institucional.",
      },
      {
        id: "tl-joao-2",
        date: "2026-06-03",
        title: "Simulação negada",
        description: "Banco Pan recusou por score baixo; retorno agendado.",
      },
    ],
  },
  {
    id: "lead-maria",
    fullName: "Maria Oliveira",
    cpf: "611.230.443-21",
    phone: "(89) 98177-4200",
    city: "Inhuma",
    hasCnh: true,
    cnhCategory: "A",
    model: "AZ125",
    desiredColor: "Branca",
    downPayment: 3200,
    paymentMethod: "Financiamento",
    seller: "Bianca",
    status: "Aprovado",
    bank: "Santander",
    lastResult: "Aprovado",
    nextActionDate: "2026-07-15",
    nextActionReason: "Enviar documentos",
    notes: "Aprovada, falta RG, comprovante de endereço e comprovante de renda.",
    visitedStore: true,
    respondsWhatsapp: true,
    returnedContact: true,
    boughtElsewhere: false,
    lastContactDate: "2026-07-14",
    createdAt: "2026-07-05",
    simulations: [
      {
        id: "sim-maria-1",
        date: "2026-07-14",
        bank: "Santander",
        result: "Aprovado",
        downPayment: 3200,
        nextActionDate: "2026-07-15",
        notes: "Parcela aprovada dentro do esperado.",
      },
    ],
    timeline: [
      {
        id: "tl-maria-1",
        date: "2026-07-05",
        title: "Primeiro contato",
        description: "Cliente pediu simulação para AZ125.",
      },
      {
        id: "tl-maria-2",
        date: "2026-07-14",
        title: "Aprovação",
        description: "Santander aprovou financiamento com entrada definida.",
      },
    ],
  },
  {
    id: "lead-jose",
    fullName: "José Pereira",
    cpf: "344.998.715-08",
    phone: "(89) 99981-6723",
    city: "Picos",
    hasCnh: false,
    cnhCategory: "Não possui",
    model: "AZ1",
    desiredColor: "Vermelha",
    downPayment: 800,
    paymentMethod: "Cartão",
    seller: "Rafael",
    status: "Aguardando Simulação",
    nextActionDate: "2026-07-16",
    nextActionReason: "Sem entrada",
    notes: "Quer ver se consegue parcelar entrada no cartão.",
    visitedStore: false,
    respondsWhatsapp: true,
    returnedContact: false,
    boughtElsewhere: false,
    lastContactDate: "2026-07-12",
    createdAt: "2026-07-12",
    simulations: [],
    timeline: [
      {
        id: "tl-jose-1",
        date: "2026-07-12",
        title: "Lead criado",
        description: "Vendedor cadastrou durante atendimento por WhatsApp.",
      },
    ],
  },
  {
    id: "lead-ana",
    fullName: "Ana Cláudia Rocha",
    cpf: "755.091.250-11",
    phone: "(89) 98821-7788",
    city: "Sussuapara",
    hasCnh: true,
    cnhCategory: "AB",
    model: "AZ160 Xtreme",
    desiredColor: "Preta",
    downPayment: 5000,
    paymentMethod: "À vista",
    seller: "Bianca",
    status: "Documentação",
    bank: "BV",
    lastResult: "Aprovado",
    nextActionDate: "2026-07-17",
    nextActionReason: "Assinar contrato",
    notes: "Negociação quente. Cliente vai à loja com o esposo.",
    visitedStore: true,
    respondsWhatsapp: true,
    returnedContact: true,
    boughtElsewhere: false,
    lastContactDate: "2026-07-15",
    createdAt: "2026-07-01",
    simulations: [
      {
        id: "sim-ana-1",
        date: "2026-07-09",
        bank: "BV",
        result: "Aprovado",
        downPayment: 5000,
        nextActionDate: "2026-07-17",
        notes: "Cliente aceitou condições.",
      },
    ],
    timeline: [
      {
        id: "tl-ana-1",
        date: "2026-07-01",
        title: "Visita à loja",
        description: "Testou posição de pilotagem e gostou da AZ160 Xtreme.",
      },
      {
        id: "tl-ana-2",
        date: "2026-07-09",
        title: "Documentação",
        description: "Contrato aprovado e documentação em conferência.",
      },
    ],
  },
  {
    id: "lead-carlos",
    fullName: "Carlos Henrique Moura",
    cpf: "168.540.601-76",
    phone: "(89) 99440-1166",
    city: "São José do Piauí",
    hasCnh: true,
    cnhCategory: "A",
    model: "AZ125",
    desiredColor: "Cinza",
    downPayment: 0,
    paymentMethod: "Consórcio",
    seller: "Lucas",
    status: "Simulação Realizada",
    bank: "Bradesco",
    lastResult: "Pendente",
    nextActionDate: "2026-07-19",
    nextActionReason: "Aguardando salário",
    notes: "Cliente recebe no fim da semana e quer revisar entrada.",
    visitedStore: false,
    respondsWhatsapp: false,
    returnedContact: false,
    boughtElsewhere: false,
    lastContactDate: "2026-07-08",
    createdAt: "2026-06-28",
    simulations: [
      {
        id: "sim-carlos-1",
        date: "2026-07-15",
        bank: "Bradesco",
        result: "Pendente",
        downPayment: 0,
        nextActionDate: "2026-07-19",
        notes: "Banco pediu atualização de renda.",
      },
    ],
    timeline: [
      {
        id: "tl-carlos-1",
        date: "2026-06-28",
        title: "Nova entrada",
        description: "Lead veio por indicação.",
      },
      {
        id: "tl-carlos-2",
        date: "2026-07-15",
        title: "Simulação pendente",
        description: "Aguardando comprovante atualizado.",
      },
    ],
  },
  {
    id: "lead-luana",
    fullName: "Luana Martins",
    cpf: "587.301.340-55",
    phone: "(89) 98130-0192",
    city: "Bocaina",
    hasCnh: true,
    cnhCategory: "AB",
    model: "AZ1",
    desiredColor: "Preta",
    downPayment: 1800,
    paymentMethod: "Financiamento",
    seller: "Lucas",
    status: "Venda Finalizada",
    bank: "Banco Pan",
    lastResult: "Aprovado",
    nextActionReason: "Pós-venda",
    notes: "Venda entregue. Fazer contato de pós-venda em 7 dias.",
    visitedStore: true,
    respondsWhatsapp: true,
    returnedContact: true,
    boughtElsewhere: false,
    lastContactDate: "2026-07-13",
    createdAt: "2026-06-18",
    closedAt: "2026-07-13",
    simulations: [
      {
        id: "sim-luana-1",
        date: "2026-06-28",
        bank: "Banco Pan",
        result: "Aprovado",
        downPayment: 1800,
        notes: "Aprovada na segunda tentativa.",
      },
    ],
    timeline: [
      {
        id: "tl-luana-1",
        date: "2026-06-18",
        title: "Lead criado",
        description: "Cliente queria uma moto econômica para deslocamento.",
      },
      {
        id: "tl-luana-2",
        date: "2026-07-13",
        title: "Venda finalizada",
        description: "AZ1 entregue com financiamento aprovado.",
      },
    ],
  },
];

export const activities: Activity[] = [
  {
    id: "act-1",
    time: "08:45",
    type: "entrada",
    leadName: "José Pereira",
    description: "Novo lead cadastrado para AZ1 vermelha.",
  },
  {
    id: "act-2",
    time: "09:30",
    type: "simulação",
    leadName: "Carlos Henrique Moura",
    description: "Simulação no Bradesco ficou pendente.",
  },
  {
    id: "act-3",
    time: "10:10",
    type: "aprovação",
    leadName: "Maria Oliveira",
    description: "Financiamento aprovado pelo Santander.",
  },
  {
    id: "act-4",
    time: "11:20",
    type: "venda",
    leadName: "Luana Martins",
    description: "Venda marcada como finalizada.",
  },
];
